#!/opt/edx/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'newrelic==1.8.0.13','console_scripts','newrelic-admin'
__requires__ = 'newrelic==1.8.0.13'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('newrelic==1.8.0.13', 'console_scripts', 'newrelic-admin')()
    )
